# Code formatting config

# The edition of Rust that the project is using.
edition = "2024"

# Ideal width of each line (default is 80).
max_width = 100

# Number of spaces per tab (default is 4).
tab_spaces = 4
hard_tabs = false

# Controls how imports are grouped and ordered.
imports_granularity = "Crate" # e.g., use std::*; use crate::*;
group_imports = "StdExternalCrate" # Groups std, external crates, and project crates separately
reorder_imports = true

# Use the shorthand syntax for field initialization (e.g., struct S { field }; instead of struct S { field: field };).
use_field_init_shorthand = true

# Formatting of comments.
wrap_comments = true
format_code_in_doc_comments = true
comment_width = 100

# Trailing commas in multi-line structures (e.g., function arguments, struct literals).
trailing_comma = "Vertical" # Adds a trailing comma if the item is vertically formatted.

# Determines where braces are placed.
fn_brace_style = "SameLineWhere"
item_brace_style = "SameLineWhere"
